# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop", 'release/**' ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1.20.0
      with:
        swift-version: 5.7.1
    - uses: actions/checkout@v3
    - name: Test
      run: swift test -v
